version: '2'
services:
  db:
    image: postgres:9.6
  python:
    build: ./CArdDog/docker/python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./CArdDog:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  node:
    image: node:10.7.0
    volumes:
      - "./CArDRabbit:/src"
      - ".docker_node_modules:/src/node_modules"
    working_dir: /src
    command: [sh, -c, yarn install && yarn run dev]
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.15.5
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "8080:8080"
    links:
      - node
      - python

